### PR TITLE
Add some hosts for Tumblr

### PR DESCRIPTION
**Pull request by DaleXiao**
Added a bunch of Tumblr hosts which work for both browser and client.

The first 9 lines leveraged from the contribution of @laodcn

### CODE REVIEW

**Comment by Too-Naive** [comment]
Thx! But the time?

**Comment by DaleXiao** [comment]
What do you mean by time? Tumblr has been banned about 2 days ago...

**Comment by lautis0503** [comment]
Line 3: Last update

**Comment by DaleXiao** [comment]
got ya, will fix it shortly when back to my desk.

**Comment by DaleXiao** [comment]
Done the time change as requested.

**Comment by DaleXiao** [comment]
can you please kindly merge the changes? @Too-Naive

**Comment by Too-Naive** [comment]
被抢先了【无奈脸】

**Pull request merged**
