### PR TITLE
add package.json file for npm install(NodeJS project)

### PR DESCRIPTION
**Pull request by cenfun**
add package.json file for npm install(NodeJS project)

### CODE REVIEW

**Comment by lrinQVQ** [comment]
this file will auto generate for npm install,we don't need add this

**Comment by lrinQVQ** [comment]
thanks commit~

**Comment by DDoSolitary** [comment]
We don't need the a `package.json` at all because there is no Node.js code in the `master` branch.

**Comment by cenfun** [comment]
It's OK.
I will think about maybe other solution to install "hosts" as nodejs dependency.
Or if you can provide something like "node_hosts" that would be great.

**Comment by DDoSolitary** [comment]
@cenfun I'm sorry but I didn't get you.
Could you please explain how a `node_hosts` package can be used?

**Comment by cenfun** [comment]
@DDoSolitary  I have a NodeJS project "[hosts_proxy](https://github.com/cenfun/hosts_proxy)",  it's a DNS proxy and used static hosts from your racaljk/hosts. we don't want to update it manually and whether it is possible automatic update by npm install.

**Comment by DDoSolitary** [comment]
@cenfun I'm sorry but currently I don't have any plans for something like this.
I don't think it is a good idea for a DNS proxy to be coupled with a specific hosts file. Using an existing DNS server software and update the hosts file using some other mechanisms(e.g. shell scripts, cron) should be enough. Creating a such a new project, in my opinion, is reinventing the wheel.

**Pull request closed without merging**
