### PR TITLE
Remove Space that will judge the root mistakenly

### PR DESCRIPTION
**Pull request by wallena3**

### CODE REVIEW

**Comment by imcaffrey** [comment]
Thanks!

**Comment by imcaffrey** [comment]
@K-Guan need your ideas

**Comment by K-Guan** [comment]
What's wrong  with that space? Will this program crashed because that space?

**Comment by wallena3** [comment]
Yes,body.I test it on Ubuntu15.10.Here are errors I met.

`sh ./script_tool_for_linux.sh
./script_tool_for_linux.sh: 2: [: ==: unexpected operator
permission denied, are you root?`

and when I remove that space,it can be correctly work.

`sh ./script_tool_for_linux.sh 
--2016-03-03 20:00:01--  https://raw.githubusercontent.com/racaljk/hosts/master/hosts
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 103.245.222.133
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|103.245.222.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 141972 (139K) [text/plain]
正在保存至: “fetchedhosts”

fetchedhosts        100%[=====================>] 138.64K   507KB/s   用时 0.3s 

2016-03-03 20:00:04 (507 KB/s) - 已保存 “fetchedhosts” [141972/141972])

Success.
`

Good Day:)

**Comment by andytimes** [comment]
@K-Guan 
`if [ ${UID} ==0 ]; then`

shell 里面貌似没有 == 这种用法，可以改成

`if [ ${UID} -eq 0 ]`

**Comment by K-Guan** [comment]
@andytimes 实际 `if [ $UID == 0 ]; then` 是没问题的，关键在于 “`bash` or **`sh`**”。如果使用 `bash` 运行脚本的话则没有问题，而 @wallena3 是用的 `sh` - 一般系统的 `sh` 应该是 `csh`，不“完全”兼容 `bash` 语法。

**Comment by wallena3** [comment]
@K-Guan  ThankU so much

**Pull request closed without merging**
