### PR TITLE
Fix little bug of Hosts Tool for Windows Console

### PR DESCRIPTION
**Pull request by Too-Naive**
RT

- [ ] Add some feature

### CODE REVIEW

**Comment by racaljk** [comment]
thx

另是否有兴趣加入 collaborators帮助我们维护hosts及其相关tool

**Comment by Too-Naive** [comment]
qwq 能得到您的赏识当然是滋磁阿 @racaljk

**Comment by racaljk** [comment]
done

以后就可以自行合并了o(｀ω´ )o

**Comment by Too-Naive** [comment]
qwq 谢谢您 @racaljk 我一定会好好努力(大雾

**Comment by imcaffrey** [comment]
Welcome! XD

**Comment by Too-Naive** [comment]
You're welcome.(大雾) @imcaffrey

**Pull request merged**
