### PR TITLE
Add Tumblr

### PR DESCRIPTION
**Pull request by laodcn**
Add Tumblr

### CODE REVIEW

**Comment by imcaffrey** [comment]
6882c910702fd38252f0b2f18ebcec6d7a2dad6a

**Comment by imcaffrey** [comment]
https://help.github.com/articles/syncing-a-fork/
http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

Here's how to update your fork directly from GitHub:

    Open your fork repository on GitHub.
    Click on Pull Requests .
    Click on New Pull Request . ...
    Click on switching the base (if no changes were made in the fork) or click Edit and switch the base manually.

**Comment by DaleXiao** [comment]
The host of Tumblr works only for browser, it doesn't work for Tumblr client on iOS.

**Comment by mcxinyu** [comment]
@imcaffrey This branch has conflicts that must be resolved

**Comment by imcaffrey** [comment]
Landed in https://github.com/racaljk/hosts/commit/f9b2d18cda2835d2e1145fd30205f1d77b34aab6.

**Pull request closed without merging**
