### PR TITLE
the newest hosts

### PR DESCRIPTION
**Pull request by KFAaron**
the newest hosts modified by [老D博客](http://laod.cn/hosts/2016-google-hosts.html)

### CODE REVIEW

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by imcaffrey** [comment]
So what is different?

**Comment by KFAaron** [comment]
I have changed my hosts with your newest hosts that updated at 2016.02.23, however ,recently ,I can't visit "www.google.com", .
Then I find the newest hosts that I pushed and change it, then I can visit "www.google.com".
I'm sorry for my bad english , hope you can understand what I say and accept it.





--
六十年诸佛龙象，三十年众生牛马。

在 2016-03-01 12:58:41，"SCaffrey" <notifications@github.com> 写道：


So what is different?

**Comment by imcaffrey** [comment]
英文不好可以说中文啊
你这样开的PR是不能merge进去的
你可以找一下修改了什么地方
按照你提供的信息，你可以具体的找一下Google的IP有怎样的变动，然后更新一下这个repo里hosts文件中的对应行的IP
谢谢！

**Comment by KFAaron** [comment]
我更新了hosts文件，现在都能正常访问了。已上传

**Comment by imcaffrey** [comment]
谢谢！

**Pull request closed without merging**
