### PR TITLE
Delete Tools Folder

### PR DESCRIPTION
**Pull request by Too-Naive**
#423

### CODE REVIEW

**Comment by Too-Naive** [comment]
Waiting for tools config

**Comment by Too-Naive** [comment]
@K-Guan Done. You should change the link of scripts.
windows.bat:https://raw.githubusercontent.com/racaljk/hosts/master/tools/windows.bat
lhosts:https://raw.githubusercontent.com/racaljk/hosts/master/tools/lhosts

**Comment by K-Guan** [comment]
@Too-Naive Got it, only need 5 mins.

**Comment by K-Guan** [comment]
There we go.

**Comment by Too-Naive** [comment]
@K-Guan Thanks!

**Pull request merged**
