### PR TITLE
You can't connect to some websites of Twitter by using these hosts, so I changed some

### PR DESCRIPTION
**Pull request by x12503181**
Updated the IP Address of L297(static.twitter.com), L298(help.twitter.com), and added ton.twitter.com, s.twitter.com.

### CODE REVIEW

**Comment by imcaffrey** [comment]
Thanks!
BTW, # 是用来标记issue的

**Comment by imcaffrey** [comment]
@x12503181 请同时修改一下 last-modified-date

**Comment by imcaffrey** [comment]
@K-Guan Need ideas on this PR.

**Comment by K-Guan** [comment]
@imcaffrey Nah, don't ask me about the hosts. @andytimes any ideas?

**Comment by andytimes** [comment]
https://github.com/racaljk/hosts/commit/959dd66dde8098348f8350defaaec5d3695a6182

**Pull request closed without merging**
