### PR TITLE
fix travis-ci build check and fix tumblr video

### PR DESCRIPTION
**Pull request by lrinQVQ**
fix issue https://github.com/racaljk/hosts/issues/887
fix tumblr video

### CODE REVIEW

**Comment by sqc1999** [comment]
SMG?

**Comment by lrinQVQ** [comment]
我解决下orz@Too-Naive

**Comment by lrinQVQ** [comment]
@Too-Naive 手残的我...咳咳解决了格式了

**Comment by lrinQVQ** [comment]
= =我重开一个好了...

**Pull request closed without merging**
