### PR TITLE
Add hosts tool of console program

### PR DESCRIPTION
**Pull request by Too-Naive**
Task list:
- [x] Able auto replace hosts file
- [x] Auto backup hosts file
- [ ] Run with service to auto update hosts file.

### CODE REVIEW

**Comment by Too-Naive** [comment]
之前弄错了一些东西..........然后commit有点多...........不过其他都没改 我都复原回来了
等tasklist全部弄好了再merge吧...77%

**Comment by imcaffrey** [comment]
@aofall Do you think that your commit should be included?
@Too-Naive In that case, please remember to squash the commits. Thx

**Comment by Too-Naive** [comment]
I close this PR. Open another PR for this.

**Comment by Too-Naive** [comment]
@imcaffrey 他添加的文件我已经删除 具体可以查看diff 我想我们的确需要exe, because user may haven't compiler.

**Pull request closed without merging**
