### PR TITLE
Fix DriveNotepad for Gdrive

### PR DESCRIPTION
**Pull request by lautis0503**
Fix Drive Notepad for Google drive. Drive Notepad is to edit the text files in your Google drive online.

### CODE REVIEW

**Comment by K-Guan** [comment]
`8c953efe117cb4ee14eaffe2b417623a104ce4e6`？你确定这个不是随机的什么的？

**Comment by imcaffrey** [comment]
我感觉这个是给DriveNotepad用的？

https://drivenotepad.appspot.com/

1.Drive Notepad is not affiliated with Google.是不是加在Google段里不合适？
2.是不是直接加appspot.com的好一些？

**Comment by K-Guan** [comment]
@imcaffrey 唉？你也是 Collaborator 了？Welcome to the brotherhood! *ominous music*

**Comment by imcaffrey** [comment]
@K-Guan The best birthday surprise ever.XD

WTF _ominous music_

**Comment by K-Guan** [comment]
@imcaffrey Wow, also HBD!

*Isn't ominous music a good thing?*

**Comment by imcaffrey** [comment]
@K-Guan Thanks. XD

I am just too noob to understand what you meant.

**Comment by K-Guan** [comment]
@imcaffrey Never mind, it was just a joke :P

**Comment by lautis0503** [comment]
@K-Guan 我这里试了下，不是随机的，猜测是Google为每个应用生成了一个编码；要不你也试试，应该不会是设备相关的。
@imcaffrey  我是Google drive中打开文本文件使用的，而且原本有appspot.com也是在Google段里，似乎Google有一些项目会用到appspot，这算不算相关？放在哪一段这种问题……你们商量决定？

**Comment by imcaffrey** [comment]
FYI:
https://github.com/racaljk/hosts/blob/master/hosts#L2802
https://github.com/racaljk/hosts/blob/master/hosts#L565

**Comment by imcaffrey** [comment]
@K-Guan I would like to hear your ideas.
We have previous cases about adding and app of Google.

**Comment by K-Guan** [comment]
@imcaffrey My ideas? Nothing. As I said so many times before, I'm only a *Wiki Writer* and *Issues Answerer*. I don't know how to dig hosts, so I also have no ideas on issues/pull requests about these issues.

**Comment by imcaffrey** [comment]
@K-Guan
So I guess we can merge this?

**Comment by K-Guan** [comment]
@imcaffrey Well, I think so anyway *(but don't blame me if that's bad actually - it's all your fault!)*

**Comment by imcaffrey** [comment]
All my pot.XD

**Pull request merged**
