### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by myguybetter**
1. Battle.net works fine now. No need to be redirected anymore.
2. Some domains of box.com can be resolved correctly. So deleted them.
3. Replaced some ips used for dropbox.com by official ones.
4. Twitter: Deleted some NX domains and added some. Deleted tinypic.com & twimg.co because they can be correctly resolved.
5. Google: Deleted books, video, orkut, HK plus and some l.google (NX) domains. Keyhole service (kh, khm, khmdb) and some pagead services are redirected to Google China, so deleted either.

### CODE REVIEW

**Comment by Too-Naive** [comment]
Date?

**Comment by myguybetter** [comment]
@Too-Naive Format mistake... Didn't check carefully 😞

**Comment by andytimes** [comment]
@myguybetter Squash merged, thanks.

**Comment by myguybetter** [comment]
@andytimes ;)

**Pull request merged**
